server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://10.124.102.48:8001/eureka/
  instance:
    instance-id: provider-mongodb

spring:
  application:
    name: provider-mongodb
  data:
    mongodb:
      uri: mongodb://10.124.102.42:27017/values
