server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: provider-mysql
  datasource:
    url: jdbc:mysql://10.129.4.202:3306/hefei_interface_monitor?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #mybatis配置mapper.xml文件位置以及包扫描
mybatis:
  mapper-locations: classpath*:mapper/*.xml #mapper文件扫描
  type-aliases-package: com.pingchuan.domain #别名扫描
