eureka:
  client:
    service-url:
      defaultZone: http://10.124.102.48:8001/eureka/
    register-with-eureka: false
  instance:
    instance-id: grid-api

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

spring:
  application:
    name: grid-api
  main:
    allow-bean-definition-overriding: true
server:
  port: 8003
